// Dataset schema: one source for the DDL, the editor autocomplete and the schema panel.
// Data: public/apps/sql/<table>.csv, generated by scripts/sql-dataset.mjs.
export const schema: Record<string, [column: string, type: string][]> = {
  champions: [['champion_id', 'INTEGER'], ['name', 'VARCHAR'], ['role', 'VARCHAR'], ['class', 'VARCHAR'], ['difficulty', 'INTEGER'], ['release_year', 'INTEGER']],
  items: [['item_id', 'INTEGER'], ['name', 'VARCHAR'], ['category', 'VARCHAR'], ['cost', 'INTEGER']],
  players: [['player_id', 'INTEGER'], ['summoner_name', 'VARCHAR'], ['region', 'VARCHAR'], ['rank_tier', 'VARCHAR'], ['main_role', 'VARCHAR'], ['created_at', 'DATE']],
  matches: [['match_id', 'INTEGER'], ['played_at', 'TIMESTAMP'], ['patch', 'VARCHAR'], ['queue', 'VARCHAR'], ['duration_s', 'INTEGER'], ['winning_team', 'VARCHAR']],
  participants: [['match_id', 'INTEGER'], ['player_id', 'INTEGER'], ['team', 'VARCHAR'], ['role', 'VARCHAR'], ['champion_id', 'INTEGER'], ['kills', 'INTEGER'], ['deaths', 'INTEGER'], ['assists', 'INTEGER'], ['cs', 'INTEGER'], ['gold', 'INTEGER'], ['win', 'BOOLEAN']],
  participant_items: [['match_id', 'INTEGER'], ['player_id', 'INTEGER'], ['slot', 'INTEGER'], ['item_id', 'INTEGER']],
};

export const tables = Object.keys(schema);
